1212502_1212508_1212526/Frontend_Ecommic/Controllers/HomeController.cs
using Frontend_Ecommic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Frontend_Ecommic.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            IndexModel model = new IndexModel();
            var temp = model.GetThongTinIndex();
            return View(temp);
        }
        public ActionResult Menu()
        {
            MenuModel model = new MenuModel();
            var temp = model.getDsMenu();
            return PartialView("Menuweb",temp);
        }
        public ActionResult Thongtinchitietsanpham ()
        {
            return View();
        }
        public ActionResult Sanpham()
        {
            return View();
        }
        public ActionResult Quanligiohang()
        {
            return View();
        }
        public ActionResult ThongBao()
        {
            return View();
        }
    }
}

1212502_1212508_1212526/Frontend_Ecommic/Controllers/SanphamController.cs
using Frontend_Ecommic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Frontend_Ecommic.Controllers
{
    public class SanphamController : Controller
    {
        // GET: Sanpham
        public ActionResult DanhSachSanPham(string name)
        {
            var temp = GLOBAL.getLoai(name);
            return View(temp);
        }
        public ActionResult PartialSanpham()
        {
            return View();
        }
        public ActionResult Chitietsanpham(string ID)
        {
            try
            {
                SanphamModel model = new SanphamModel();
                var temp = model.GetChiTietSanPham(Int32.Parse(ID));
                return View(temp);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
            
        }
        public ActionResult Sanphamlienquan(string ID)
        {
            SanphamModel model = new SanphamModel();
            var temp = model.GetSanPhamLQ(ID);
            return View(temp);
        }
    }
}

1212502_1212508_1212526/Frontend_Ecommic/Views/Home/FormDangki.cshtml
@model Frontend_Ecommic.Models.RegisterViewModel
@{ViewBag.Title = "Trang đăng kí ";
    <link href="~/css/FormTaiKhoan.css" rel="stylesheet" />
    List<SelectListItem> li = new List<SelectListItem>();
    li.Add(new SelectListItem { Text = "Nam", Value = "0" });
    li.Add(new SelectListItem { Text = "Nữ", Value = "1" });
    ViewData["gioitinh"] = li;
}

<div>
    @using (Html.BeginForm("Dangki", "Account", FormMethod.Post, new { @class = "sign-up" }))
    {

        <fieldset>
            <div class="login-header">
                <span>Đăng kí</span>
                <a href="#" class="close">Close</a>
            </div>
            <div class="Error">
                @if (@Session["Loi"] != null)
                {
                    <p>@Session["Loi"]</p>
                }
            </div>
            <div class="login-content">
                <label for="name">UserName:</label>
                @Html.TextBoxFor(m => m.UserName)
                @Html.ValidationMessageFor(m => m.UserName)
                <label for="pass">Password:</label>
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
                <label for="pass">Confirm:</label>
                @Html.PasswordFor(m => m.ConfirmPassword)
                @Html.ValidationMessageFor(m => m.ConfirmPassword)
                <label for="name">Email:</label>
                @Html.TextBoxFor(m => m.Email)
                @Html.ValidationMessageFor(m => m.Email)
                <label for="name">SDT:</label>
                @Html.TextBoxFor(m => m.SDT)
                @Html.ValidationMessageFor(m => m.SDT)

                <input type="submit" value="Log In" class="loginsubmit" />
            </div>
        </fieldset>
    }
</div>

1212502_1212508_1212526/Frontend_Ecommic/Views/Home/FormDangnhap.cshtml
@model Frontend_Ecommic.Models.LoginViewModel

@{
    ViewBag.Title = "Trang đăng nhập";
    <link href="~/css/FormTaiKhoan.css" rel="stylesheet" />
}

<div>
    @using (Html.BeginForm("DangNhap", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "login1" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <fieldset>
            <div class="login-header">
                <span>Đăng nhập</span>
                <a href="#" class="close">Close</a>
            </div>
            <div class="Error">
                @if (@Session["Loi"] != null)
                {
                    <p>@Session["Loi"]</p>
                }
            </div>
            <div class="login-content">
                <label for="name">UserName:</label>
                @Html.TextBoxFor(m => m.UserName)
                @Html.ValidationMessageFor(m => m.UserName)
                <label for="pass">Password:</label>
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
                @*<input type="submit" value="Log In" class="loginsubmit" />*@
               
                <div class="checkbox-inline">
                    <div>
                        @Html.CheckBoxFor(m => m.RememberMe)
                        <i>Remember me ?</i>
                        <i><a href="@Url.Action("Quenmatkhau","Home")">Forget password</a></i>
                    </div>
                </div>
                <input class="loginsubmit" type="submit" value="Log In" />
                
            </div>
        </fieldset>
    }
    @Html.Partial("_ExternalLoginsListPartial", new { Action = "LoginService", ReturnUrl = ViewBag.ReturnUrl })
</div>

1212502_1212508_1212526/Frontend_Ecommic/Views/Home/Index.cshtml
@model Frontend_Ecommic.Models.IndexModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 <div class="main-top">

    <div class="col-md-8 banner">
        <!-- start slider -->
        <!----->
        <div class="slider">
            <div class="callbacks_container">
                <ul class="rslides" id="slider">
                    @for (int i = 0; i < @Model.Sliders.Count; i++)
                    {
                        <li><img src="@Model.Sliders[i].Url" /></li>
                    }
                </ul>
            </div>
        </div>
        <!----->
        <!-- end  slider -->
    </div>
    <div class="col-md-4 right-grid">
        <div class="right-grid-top">
            <div class="r-sale text-center">
                <h6>Tuần lễ vàng</h6>
                <h2>Sale</h2>
            </div>
            <div class="r-discount">
                <span>thêm</span>
                <h2>50%</h2>
                <p>OFF</p>
                <a href="#">Mua ngay<i class="go"></i></a>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="right-grid-bottom">
            <div class="right-grid-bottom-left">
                <h3>khuyến mãi</h3>
                <p>Đến :10/5/2015</p>
                <h5>Wireless Headphones</h5>
                <h2>Giảm thêm 30%</h2>
                <a href="single.html">Mua ngay<i class="go"></i></a>
            </div>
            <div class="right-grid-bottom-right">
                <img src="images/headset.png" alt="" />
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>

<div class="new-arrivals text-center" ng-controller="truyxuatcontroller">
    <div class="col-md-3 new-arrival-head">
        <h3>Tin tuc </h3>
        <a class="btn btn-1 btn-1d" href="@Url.Action("Danhsachtintuc", "Truyxuat")">Xem tất cả</a>
    </div>
   
    <div class="col-md-3 product-item" ng-repeat="item in dsnews | limitTo: 3">
        <a href="{{item.srcPage}}"><img src="{{item.image}}" class="img-responsive" alt="" /></a>
        <h3>{{item.Title}}</h3>
        <a href="{{item.srcPage}}">Xem Ngay</a><i class="go"></i>
    </div>
    <div class="clearfix"></div>
</div>
<div class="new-arrivals text-center">
    <div class="col-md-3 new-arrival-head">
        <h3>Hàng mới </h3>
        <a class="btn btn-1 btn-1d" href="@Url.Action("Danhsachsanpham", "Sanpham", new { name = "Điện thoại" })">Xem tất cả</a>
    </div>
    @for (int i = 0; i < @Model.sanPhamMoi.Count; i++)
    {
        <div class="col-md-3 product-item">
            <a href="@Url.Action("Chitietsanpham", "Sanpham", new { ID = @Model.sanPhamMoi[i].ID })"><img src="@Frontend_Ecommic.Models.GLOBAL.urlapi@Model.sanPhamMoi[i].Duongdanhinh" class="img-responsive" alt="" /></a>
            <h3>@Model.sanPhamMoi[i].TenSanPham</h3>
            <a href="@Url.Action("Chitietsanpham", "Sanpham", new { ID = @Model.sanPhamMoi[i].ID })">Xem Ngay</a><i class="go"></i>
        </div>
    }
    <div class="clearfix"></div>
</div>
<div ng-controller="mycontroll">
    <div class="best-sellers">
        <div class="best-sellers-head">
            <h3>Bán chạy nhất</h3>
        </div>
        <div class="best-sellers-menu">
            <ul>
                @for (int i = 0; i < @Model.loaiSanPham.Count; i++)
                {
                    <li><a href="javascript:;" ng-click="changetype(@Model.loaiSanPham[i].ID,@i)" ng-class="{active : isSelected(@i)}">@Model.loaiSanPham[i].TenLoai</a></li>
                }
                <li><a>Other</a></li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="main" ng-controller="xuligiohang">
        <div class="content">
            <div class="section group">
                <div class="grid_1_of_4 images_1_of_4" ng-repeat="item in sanPham">
                    <a href="/Sanpham/Chitietsanpham/{{item.ID}}"><img src="@Frontend_Ecommic.Models.GLOBAL.urlapi{{item.Duongdanhinh}}" class="img-responsive" alt="" /></a>
                    <h3>{{item.TenSanPham}}</h3>
                    <p><span class="price">{{item.Giatien}}</span></p>
                    <div class="button"><span><a href="javascript:;" ng-click="addtoCart(item.ID)" class="cart-button">Add to Cart</a></span> </div>
                    <div class="button"><span><a href="/Sanpham/Chitietsanpham/{{item.ID}}" class="details">Details</a></span></div>
                </div>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<div class="clients">
    <div class="course_demo1">
        <ul id="flexiselDemo1">
            <li>
                <div class="client">
                    <img src="images/l1.jpg" alt="" />
                </div>
            </li>
            <li>
                <div class="client">
                    <img src="images/l2.jpg" alt="" />
                </div>
            </li>
            <li>
                <div class="client">
                    <img src="images/l3.jpg" alt="" />
                </div>
            </li>
            <li>
                <div class="client">
                    <img src="images/l4.jpg" alt="" />
                </div>
            </li>
            <li>
                <div class="client">
                    <img src="images/l5.jpg" alt="" />
                </div>
            </li>
            <li>
                <div class="client">
                    <img src="images/l6.jpg" alt="" />
                </div>
            </li>
            <li>
                <div class="client">
                    <img src="images/l7.jpg" alt="" />
                </div>
            </li>
            <li>
                <div class="client">
                    <img src="images/l9.jpg" alt="" />
                </div>
            </li>
        </ul>
    </div>

    
    
</div>
<div class="transport-grid">
    <div class="col-md-4 shipping">
        <h3><i class="shipping-icon"></i>Miễn phí vận chuyển</h3>
        <p>Chúng tôi vận chuyển an toàn ,uy tín, không hao hụt sản phẩm , và chuyển đến tận tay người mua</p>
    </div>
    <div class="col-md-4 shipping">
        <h3><i class="correct-icon"></i>100 % chính hãng</h3>
        <p>Chúng tôi cam kết luôn luôn bán hàng chính hãng </p>
    </div>
    <div class="col-md-4 return">
        <h3><i class="return-icon"></i>Miễn phí đổi trả</h3>
        <p>Vì bất cứ lí do gì bạn không thích máy của mình mà còn trong hạn đổi trả, chúng tôi xin hân hạnh đón tiếp bạn</p>
    </div>
    <div class="clearfix"></div>
</div>

1212502_1212508_1212526/Frontend_Ecommic/Views/Home/Menuweb.cshtml
@model List<Frontend_Ecommic.Models.MenuModel>
@{
    Layout = null;
}
<ul class="megamenu skyblue">
    @for (int i = 0; i < @Model.Count; i++)
    {
        <li>
            <a class="color1" href="@Url.Action("DanhSachSanPham","Sanpham", new { name = @Model[i].Name })">@Model[i].Name</a>
            <div class="megapanel">
                <div class="row">
                    <div class="col1">
                        <div class="h_nav">
                            <h4>Hãng sản xuất</h4>
                            <ul>
                                @for (int j = 0; j < @Model[i].subMenu.Count; j++)
                                {
                                    <li><a href="@Url.Action("DanhSachSanPham","Sanpham", new { name = @Model[i].Name, submenu = @Model[i].subMenu[j].Name })">@Model[i].subMenu[j].Name</a></li>
                                }

                            </ul>
                        </div>
                    </div>
                    <div class="col3">
                        <div class="h_nav">
                            <ul>
                                <li><img src="~/images/dt3.jpg" alt="" width="300px" height="300px" /></li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>

        </li>
    }
</ul>

1212502_1212508_1212526/Frontend_Ecommic/Views/Home/Quanligiohang.cshtml
@{
    ViewBag.Title = "Quanligiohang";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <link href="~/css/Style_tintuc.css" rel="stylesheet" />
}

<body>
    <!-- start main -->
    <div class="main_bg">
        <div class="main">
            <div class="left_content">
                <div class="mycart">
                    <h3>Thông tin giỏ hàng</h3>
                    <div class="quanli">
                        <div class="simpleCart_items">
                            @for (int i = 0; i < @Model.Count; i++)
                            {
                                <div class="itemContainer">
                                    <div class="itemname">@Model[i].Sanpham.TenSanPham</div>
                                    <div class="itemthumb">
                                        <img src="../../@Model[i].Sanpham.Duongdanhinh" alt="img" />
                                    </div>
                                    <div class="itemQuantity">
                                        <select onchange="changequantity(this.value,@i);">
                                            @for (int j = 1; j <= @Model[i].Sanpham.Soluong; j++)
                                            {
                                                if (j == Model[i].Soluong)
                                                {
                                                    <option value="@j" selected>@j</option>
                                                }
                                                else
                                                {
                                                    <option value="@j">@j</option>
                                                }
                                            }
                                        </select>

                                    </div>
                                    <div class="itemcolor">
                                        Color :
                                        <select onchange="changecolor(this.value,@i);">
                                            @for (int j = 0; j < @Model[i].Sanpham.Colors.Count; j++)
                                            {
                                                if (Model[i].Sanpham.Colors.ToList()[j].Ten == Model[i].color)
                                                {
                                                    <option value="@Model[i].Sanpham.Colors.ToList()[j].Ten" selected>@Model[i].Sanpham.Colors.ToList()[j].Ten</option>
                                                }
                                                else
                                                {
                                                    <option value="@Model[i].Sanpham.Colors.ToList()[j].Ten">@Model[i].Sanpham.Colors.ToList()[j].Ten</option>
                                                }
                                            }
                                        </select>
                                    </div>
                                    <div class="itemTotal">
                                        VND : @Model[i].Dongia
                                    </div>
                                    <div class="itemremove">
                                        <a href="javascript:;" onclick="javacript:Loaibo(@i);">Loại bỏ</a>
                                    </div>
                                </div>
                            }
                            <div class="clear"></div>
                            <div class="mycartinfo">
                                <table>
                                    <tbody>
                                        <tr><td class="title">Số lượng: </td><td class="numb"><span class="simpleCart_quantity">@Session["soluong"]</span></td></tr>
                                        <tr><td class="title">Thành tiền: </td><td class="numb"><span class="simpleCart_total">VND&nbsp;@Session["tongtien"]</span></td></tr>
                                        <tr><td class="title">Phí ship: </td><td class="numb"><span class="simpleCart_shippingCost">VND&nbsp;0.00</span></td></tr>
                                        <tr><td class="title">Tổng cộng: </td><td class="numb"><span class="simpleCart_finalTotal">VND&nbsp;@Session["tongtien"]</span></td></tr>
                                    </tbody>
                                </table>
                                <div class="clear"></div>
                                <div class="button_check">
                                    <a class="simpleCart_empty" href="javascript:;" onclick="Deleteall();" title="Xóa hết đơn hàng">Xóa hết</a>
                                    <a class="thanhtoan" href="javascript:;" onclick="Thanhtoanform();">Thanh toán</a>
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
                <div class="form-tt">

                </div>
            </div>


            <div class="sub-cate single-subcate">
                <div class=" top-nav rsidebar span_1_of_left">
                    <h3 class="cate">CATEGORIES</h3>
                    <ul class="menu">
                        <li class="item1">
                            <a href="#">Danh sách<img class="arrow-img" src="~/images/arrow1.png" alt="" /> </a>
                            <ul class="cute">
                                <li class="subitem1"><a href="@Url.Action("Sanphammoira","T2V_")">Mới ra </a></li>
                            </ul>
                        </li>
                        <li>
                            <ul class="kid-menu">
                                <li><a href="@Url.Action("Danhsachsanpham", new { name = "Phụ Kiện" })">Danh sách Phụ kiện </a></li>
                                <li class="menu-kid-left">@Html.ActionLink("Liên hệ chúng tôi", "Thongtinnhom")</li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!--initiate accordion-->
                <script type="text/javascript">
                    $(function () {
                        var menu_ul = $('.menu > li > ul'),
                               menu_a = $('.menu > li > a');
                        menu_ul.hide();
                        menu_a.click(function (e) {
                            e.preventDefault();
                            if (!$(this).hasClass('active')) {
                                menu_a.removeClass('active');
                                menu_ul.filter(':visible').slideUp('normal');
                                $(this).addClass('active').next().stop(true, true).slideDown('normal');
                            } else {
                                $(this).removeClass('active');
                                $(this).next().stop(true, true).slideUp('normal');
                            }
                        });

                    });
                </script>
                @if (@Session["newproduct"] != null)
                {
                    @Html.Partial("sanphamquancao", @Session["newproduct"])
                }
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>

    </div>
</body>
<script type="text/javascript">

    function Loaibo(value) {
        var url = '@Url.Action("Loaikhoigiohang","Xuli")';
        $.ajax({
            url: url,
            type: 'POST',
            cache: false,
            data: { a: value },
            success: function (result) {
                $('.quanli').html(result.toString());
            },
        });
    }
    function changequantity(value, value1) {
        var url = '@Url.Action("ChangeQuanity", "Xuli")';
        $.ajax({
            url: url,
            type: 'POST',
            cache: false,
            data: { a: value, b: value1 },
            success: function (result) {
                $('.quanli').html(result.toString());
            },
        });
    }
    function changecolor(value, value1) {
        var url = '@Url.Action("Changecolor", "Xuli")';
        $.ajax({
            url: url,
            type: 'POST',
            cache: false,
            data: { a: value, b: value1 },
            success: function (result) {
            },
        });
    }
    function Deleteall() {
        var url = '@Url.Action("Deleteall", "Xuli")';
        $.ajax({
            url: url,
            type: 'POST',
            cache: false,
            data: {},
            success: function (result) {
                $('.quanli').html(result.toString());
                $('.last').html("0");
            },
        });
    }
    function Thanhtoanform() {
        var url = '@Url.Action("Formthanhtoan", "Xuli")';
        if('@Session["islogin"]' == "N")
        {
            var login = $('.login1');
            var signup = $('.sign-up');
            var body = $('body');
            body.css({ 'overflow': 'hidden' });
            login.fadeIn(500)
        }
        else
        {
            $.ajax({
                url: url,
                type: 'POST',
                cache: false,
                data: {},
                success: function (result) {
                    $('.form-tt').html(result.toString());
                },
            });
        }
    }

</script>

1212502_1212508_1212526/Frontend_Ecommic/Views/Home/Sanpham.cshtml
@{
    ViewBag.Title = "Sanpham";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content">
    <div class="content_top">
        <div class="heading">
            <h3>Điện thoại</h3>
        </div>
        <div class="sort">
            <p>
                Sắp xếp:
                <select>
                    <option>Giá tăng</option>
                    <option>Giá giảm</option>
                    <option>Còn hàng</option>
                </select>
            </p>
        </div>
        <div class="show">
            <p>
                Hiển thị:
                <select>
                    <option>4</option>
                    <option>8</option>
                    <option>12</option>
                    <option>16</option>
                    <option>20</option>
                    <option>In Stock</option>
                </select>
            </p>
        </div>
        <div class="page-no">
            <p>
                Result Pages:<ul>
                    <li><a href="#">1</a></li>
                    <li class="active"><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li>[<a href="#"> Next>>></a>]</li>
                </ul>
            </p>
        </div>
        <div class="clearfix"></div>
    </div>
    @for (int i = 0; i < @Model.LayDanhSachTheoLoaiSanPham("Điện thoại").Count; i = i + 4)
    {
        <div class="section group">
            @for (int j = i; j < i + 4; j++)
            {
                if (j == @Model.LayDanhSachTheoLoaiSanPham("Điện thoại").Count)
                {
                    break;
                }
                <div class="grid_1_of_4 images_1_of_4">
                    <a href="#"><img src="@Model.LayDanhSachTheoLoaiSanPham("Điện thoại")[j].Linkimage" class="img-responsive" alt="" /></a>
                    <h3>@Model.LayDanhSachTheoLoaiSanPham("Điện thoại")[j].Tensanpham</h3>
                    <p><span class="price">@Model.LayDanhSachTheoLoaiSanPham("Điện thoại")[j].Giatien</span></p>
                    <div class="button"><span><a href="#" class="cart-button">Add to Cart</a></span> </div>
                    <div class="button"><span><a href="#" class="details">Details</a></span></div>
                </div>
            }
            <div class="clearfix"></div>
        </div>
    }
</div>

1212502_1212508_1212526/Frontend_Ecommic/Views/Home/ThongBao.cshtml
@{
    ViewBag.Title = "ThongBao";
}

<h2>Chat</h2>
<div class="container">
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />
    <input type="hidden" id="displayname" />
    <ul id="discussion"></ul>
</div>
@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.notifiHub;
            // Create a function that the hub can call back to display messages.
            chat.client.addNewMessageToPage = function (name, message) {
                // Add the message to the page.
                $('#discussion').append('<li><strong>' + htmlEncode(name)
                    + '</strong>: ' + htmlEncode(message) + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                });
            });
        });
        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
    </script>
}

1212502_1212508_1212526/Frontend_Ecommic/Views/Home/_ExternalLoginsListPartial.cshtml
@using Microsoft.Owin.Security

<h4>Use another service to log in.</h4>
<hr />
@{
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0)
    {
        <div>
            <p>Hiện tại chưa có.</p>
        </div>
    }
    else
    {
        string action = Model.Action;
        string returnUrl = Model.ReturnUrl;
        using (Html.BeginForm(action, "Account", new { ReturnUrl = returnUrl }, FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div id="socialLoginList">
                <p>
                    @foreach (AuthenticationDescription p in loginProviders)
                    {
                        <button type="submit" class="btn btn-default" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" title="Log in using your @p.Caption account">@p.AuthenticationType</button>
                    }
                </p>
            </div>
        }
    }
}