1212502_1212508_1212526/Frontend_Ecommic/Controllers/AccountManagerController.cs
using Frontend_Ecommic.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace Frontend_Ecommic.Controllers
{
    public class AccountManagerController : Controller
    {
        //
        // GET: /AccountManager/
        public ActionResult Index(ViewModel model)
        {
            if (Request.Cookies.Get("UserName") != null && Request.Cookies.Get("Password") != null)
            {
                if (model.LoginModel == null)
                    model.LoginModel = new LoginViewModel();
                model.LoginModel.UserName = Request.Cookies["UserName"].Value;
                model.LoginModel.Password = Request.Cookies["Password"].Value;
                model.LoginModel.RememberMe = true;
            }
            return View(model);
        }

        public ActionResult DangNhap(ViewModel model, string returnUrl)
        {
            using (HttpClient Client = new HttpClient())
            {
                string url = "api/account/login";
                Client.BaseAddress = new Uri(GLOBAL.urlapi);
                Client.DefaultRequestHeaders.Accept.Clear();
                Client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json")
                );
                // get slides
                var value = new { Username = model.LoginModel.UserName, Password = model.LoginModel.Password };
                HttpResponseMessage response = Client.PostAsJsonAsync(url, value).Result;
                if (response.IsSuccessStatusCode)
                {
                    if (model.LoginModel.RememberMe == true)
                    {
                        Response.Cookies["UserName"].Value = model.LoginModel.UserName;
                        Response.Cookies["Password"].Value = model.LoginModel.Password;
                    }
                    var token = response.Content.ReadAsAsync<AccessToken>().Result;
                    Session["Access_Token"] = token;
                    Session.Remove("Google");
                    Session["notice"] = "Đăng nhập thành công!";
                    Session.Remove("LoiDangNhap");
                    Session.Remove("LoiDangKi");
                    Client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.access_token);
                    HttpResponseMessage response1 = Client.GetAsync("api/account/IsAdmin").Result;
                    var infor = response1.Content.ReadAsAsync<bool>().Result;
                    if (infor == true)
                    {
                        Session["Admin"] = true;
                    }
                }
                else
                {
                    Session["LoiDangNhap"] = "Thông tin đăng nhập sai!";
                    Session.Remove("LoiDangKi");
                    return RedirectToAction("Index", model);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult DangKi(ViewModel model, string returnUrl)
        {
            if (model.RegisterModel.Password == model.RegisterModel.ConfirmPassword)
            {
                using (HttpClient Client = new HttpClient())
                {
                    string url = "api/account/register";
                    Client.BaseAddress = new Uri(GLOBAL.urlapi);
                    Client.DefaultRequestHeaders.Accept.Clear();
                    Client.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json")
                    );
                    // get slides
                    var value = new { Username = model.RegisterModel.UserName, Password = model.RegisterModel.Password, ConfirmPassword = model.RegisterModel.ConfirmPassword, Email = model.RegisterModel.Email, SDT = model.RegisterModel.SDT };
                    HttpResponseMessage response = Client.PostAsJsonAsync(url, value).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var token = response.Content.ReadAsAsync<AccessToken>().Result;
                        Session["Access_Token"] = token;
                        Session.Remove("LoiDangNhap");
                        Session.Remove("LoiDangKi");
                        Session.Remove("Google");
                    }
                    else
                    {
                        Session["LoiDangKi"] = "Thông tin đăng kí sai!";
                        Session.Remove("LoiDangNhap");
                        return RedirectToAction("Index", model);
                    }
                }
            }
            else
            {
                Session["LoiDangKi"] = "Thông tin đăng kí sai!";
                Session.Remove("LoiDangNhap");
                return RedirectToAction("Index", model);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Dangxuat()
        {
            Session.Remove("Access_Token");
            Session.Remove("Admin");
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Thongtincanhan()
        {
            InforViewModel model = new InforViewModel();
            model.information = new InformationModel();
            model.editPassModel = new EditPassModel();
            AccessToken token = (AccessToken)Session["Access_Token"];
            string a = (string)Session["Doimatkhau"];
            using (HttpClient Client = new HttpClient())
            {
                string url = "api/account/Information";
                Client.BaseAddress = new Uri(GLOBAL.urlapi);
                Client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.access_token);
                Client.DefaultRequestHeaders.Accept.Clear();
                Client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json")
                );
                // get slides
                HttpResponseMessage response = Client.GetAsync(url).Result;
                if (response.IsSuccessStatusCode)
                {
                    var infor = response.Content.ReadAsAsync<Information>().Result;

                    model.information.UserName = infor.UserName;
                    model.information.Diachi = infor.Diachi;
                    if(infor.Gioitinh != "Nam")
                        model.information.Gioitinh = 1;
                    else
                        model.information.Gioitinh = 0;
                    model.information.HoTen = infor.HoTen;
                    if (infor.Namsinh != null)
                    {
                        string formatted = infor.Namsinh.ToString();
                        model.information.Namsinh = DateTime.Parse(formatted);
                    }
                    if (infor.Ngaydangki != null)
                    {
                        string formatted1 = infor.Ngaydangki.ToString();
                        model.information.Ngaydangki = DateTime.Parse(formatted1);

                    }
                    model.information.SDT = infor.SDT;
                    model.information.Email = infor.Email;
                    model.information.Anhdaidien = infor.Anhdaidien;
                    return View(model);
                }
                else
                {

                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Thongtincanhan(InforViewModel model,string UserName, string SDT, string Email, string Anhdaidien)
        {
            model.information.UserName = UserName;
            model.information.SDT = SDT;
            model.information.Email = Email;
            model.information.Anhdaidien = Anhdaidien;
            AccessToken token = (AccessToken)Session["Access_Token"];
            string a = (string)Session["Doimatkhau"];
            using (HttpClient Client = new HttpClient())
            {
                string url = "api/account/EditInformation";
                Client.BaseAddress = new Uri(GLOBAL.urlapi);
                Client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.access_token);
                Client.DefaultRequestHeaders.Accept.Clear();
                Client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json")
                );
                var value = new { UserName = model.information.UserName, HoTen = model.information.HoTen, Gioitinh = model.information.Gioitinh, Namsinh = model.information.Namsinh, Diachi = model.information.Diachi, SDT = model.information.SDT, Anhdaidien = model.information.Anhdaidien, Ngaydangki = model.information.Ngaydangki, Email = model.information.Email };
                // get slides
                HttpResponseMessage response = Client.PostAsJsonAsync(url, value).Result;
                if (response.IsSuccessStatusCode)
                {

                }
                else
                {

                }
            }
            return RedirectToAction("Thongtincanhan");
        }

        public ActionResult Taikhoangoogle()
        {
            ExternalLoginInfoModels model = new ExternalLoginInfoModels();
            if (Session["Google"] != null)
            {
                var infor = (ExternalLoginInfo)Session["Google"];
                model.DefaultUserName = infor.DefaultUserName;
                model.Email = infor.Email;
                model.ExternalIdentity = infor.ExternalIdentity;
                model.Login = infor.Login;
            }

            return View(model);
        }

        public ActionResult Thaydoimatkhau(InforViewModel model)
        {

1212502_1212508_1212526/Frontend_Ecommic/Views/AccountManager/Index.cshtml
@model Frontend_Ecommic.Models.ViewModel
@{
    ViewBag.Title = "Index";
    <link href="~/Content/css/Account.css" rel="stylesheet" />
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-6">
                        <div class="account-id">
                            <h4 class="account-title">
                                <span class="fa fa-chevron-right"></span>
                                Đăng nhập
                            </h4>
                            <div class="account-form">
                                @using (Html.BeginForm("DangNhap", "AccountManager", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)
                                    <fieldset>
                                        <div class="Error">
                                            @if (@Session["LoiDangNhap"] != null)
                                            {
                                                <p>@Session["LoiDangNhap"]</p>
                                            }
                                        </div>
                                        <div class="login-content">
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">UserName <span class="required">*</span></label>
                                                @Html.TextBoxFor(m => @Model.LoginModel.UserName)
                                                @Html.ValidationMessageFor(m => @Model.LoginModel.UserName)
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <label for="pass">Password <span class="required">*</span></label>
                                                @Html.PasswordFor(m => @Model.LoginModel.Password)
                                                @Html.ValidationMessageFor(m => @Model.LoginModel.Password)
                                                @*<input type="submit" value="Log In" class="loginsubmit" />*@
                                            </div>
                                            <div class="col-md-6 col-sm-12">
                                                <div>
                                                    <label for="rememberme" class="inline">@Html.CheckBoxFor(m => @Model.LoginModel.RememberMe) Remember me ?</label>
                                                </div>
                                            </div>
                                            <div class="col-md-6 col-sm-12">
                                                <div>
                                                    <label for="forgetpassword" class="inline"><a href="@Url.Action("Quenmatkhau","AccountManager")">Forget password?</a></label>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="buttons-set">
                                            <input class="btn-black" name="action" type="submit" value="Đăng nhập" />
                                        </div>
                                    </fieldset>
                                }
                            </div>
                        </div>
                        
                    </div>
                    <div class="col-sm-6 col-md-6">
                        <div class="account-id">
                            <h4 class="account-title">
                                <span class="fa fa-chevron-right"></span>
                                Đăng kí
                            </h4>
                            @{
                                Frontend_Ecommic.Models.RegisterViewModel registerModel = new Frontend_Ecommic.Models.RegisterViewModel();
                                <div class="account-form">
                                    @using (Html.BeginForm("Dangki", "AccountManager", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.ValidationSummary(true)
                                        <fieldset>
                                            <div class="Error">
                                                @if (@Session["LoiDangKi"] != null)
                                                {
                                                    <p>@Session["LoiDangKi"]</p>
                                                }
                                            </div>
                                            <div class="login-content">
                                                <div class="col-md-12 col-sm-12">
                                                    <label for="name">UserName <span class="required">*</span></label>
                                                    @Html.TextBoxFor(m => @Model.RegisterModel.UserName)
                                                    @Html.ValidationMessageFor(m => @Model.RegisterModel.UserName)
                                                </div>
                                                <div class="col-md-12 col-sm-12">
                                                    <label for="pass">Password <span class="required">*</span></label>
                                                    @Html.PasswordFor(m => @Model.RegisterModel.Password)
                                                    @Html.ValidationMessageFor(m => @Model.RegisterModel.Password)
                                                </div>
                                                <div class="col-md-12 col-sm-12">
                                                    <label for="pass">Confirm <span class="required">*</span></label>
                                                    @Html.PasswordFor(m => @Model.RegisterModel.ConfirmPassword)
                                                    @Html.ValidationMessageFor(m => @Model.RegisterModel.ConfirmPassword)
                                                </div>
                                                <div class="col-md-12 col-sm-12">
                                                    <label for="name">Email <span class="required">*</span></label>
                                                    @Html.TextBoxFor(m => @Model.RegisterModel.Email)
                                                    @Html.ValidationMessageFor(m => @Model.RegisterModel.Email)
                                                </div>
                                                <div class="col-md-12 col-sm-12">
                                                    <label for="name">SDT <span class="required">*</span></label>
                                                    @Html.TextBoxFor(m => @Model.RegisterModel.SDT)
                                                    @Html.ValidationMessageFor(m => @Model.RegisterModel.SDT)
                                                </div>
                                            </div>
                                            <div class="buttons-set">
                                                <input type="submit" name="action" value="Đăng kí" class="btn-black" />
                                            </div>
                                        </fieldset>
                                    }
                                </div>
                            }
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-6">
                        <div class="account-id">
                            <h4 class="account-title">
                                <span class="fa fa-chevron-right"></span>
                                Đăng nhập với dịch vụ khác
                            </h4>
                        </div>
                        <div class="account-form">
                            @using (Html.BeginForm("Login", "Account", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true)
                                <fieldset>
                                    <div class="Error">
                                        @if (@Session["LoiDangKi"] != null)
                                        {
                                            <p>@Session["LoiDangKi"]</p>
                                        }
                                    </div>
                                    <div class="buttons-set">
                                        <input type="submit" name="action" value="Google" class="btn-black" />
                                    </div>
                                </fieldset>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

1212502_1212508_1212526/Frontend_Ecommic/Views/AccountManager/Taikhoangoogle.cshtml
@model Frontend_Ecommic.Models.ExternalLoginInfoModels
@{
    ViewBag.Title = "Taikhoangoogle";
    <link href="~/Content/css/Account.css" rel="stylesheet" />
}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-6">
                        <div class="account-id">
                            <h4 class="account-title">
                                <span class="fa fa-chevron-right"></span>
                                Thông tin cá nhân
                            </h4>
                            
                            <div class="account-form">
                                <fieldset>
                                        <div class="Error">
                                        </div>
                                        <div class="login-content">
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">Tài khoản: @Model.DefaultUserName</label>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <label for="pass">Email: @Model.Email </label>
                                            </div>
                                        </div>
                                </fieldset>
                            </div>
                        </div>

                    </div>
                    <div class="col-sm-6 col-md-6">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

1212502_1212508_1212526/Frontend_Ecommic/Views/AccountManager/Thongtincanhan.cshtml
@model Frontend_Ecommic.Models.InforViewModel
@{
    ViewBag.Title = "Thông tin cá nhân";
    <link href="~/Content/css/Account.css" rel="stylesheet" />
     <link href="@Url.Content("~/Content/themes/base/jquery.ui.core.css")" 
        rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.datepicker.css")" 
        rel="stylesheet"  type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.theme.css")" 
        rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery.ui.core.min.js")" 
        type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.ui.datepicker.min.js")" 
        type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/DatePickerReady.js")" 
        type="text/javascript"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script type="text/javascript">
        $(function () {
            $(".news_date").datepicker();
        });
    </script>
}
<script type="text/javascript">
    $(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $('.datetimepicker').datetimepicker();
    })
</script>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-6">
                        <div class="account-id">
                            <h4 class="account-title">
                                <span class="fa fa-chevron-right"></span>
                                Thông tin cá nhân
                            </h4>
                            <div class="account-form">
								@using (Html.BeginForm("Thongtincanhan", "AccountManager", new { ReturnUrl = ViewBag.ReturnUrl, UserName = @Model.information.UserName, SDT = @Model.information.SDT, Email = @Model.information.Email, Anhdaidien = @Model.information.Anhdaidien  }, FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)
                                    <fieldset>
                                        <div class="Error">
                                            @if (@Session["Doithongtin"] != null)
                                            {
                                                <p>@Session["Doithongtin"]</p>
                                            }
                                        </div>
                                        <div class="login-content">
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">Họ tên </label>
                                                @Html.TextBoxFor(m => @Model.information.HoTen)
                                                @Html.ValidationMessageFor(m => @Model.information.HoTen)
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                @{List<SelectListItem> gioitinh = new List<SelectListItem>();
                                                  gioitinh.Add(new SelectListItem
                                                  {
                                                      Text = "Nam",
                                                      Value = "0"
                                                  });

                                                  gioitinh.Add(new SelectListItem
                                                  {
                                                      Text = "Nữ",
                                                      Value = "1"
                                                  });
                                                }
                                                <label for="pass">Giới tính </label>
                                                @Html.DropDownListFor(m => @Model.information.Gioitinh, gioitinh)
                                                @*<input type="submit" value="Log In" class="loginsubmit" />*@
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">Ngày sinh </label>
                                                @Html.TextBoxFor(m => @Model.information.Namsinh, "", new { @class = "form-control datetimepicker news_date" })
                                                @Html.ValidationMessageFor(m => @Model.information.Namsinh)
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">Địa chỉ </label>
                                                @Html.TextBoxFor(m => @Model.information.Diachi)
                                                @Html.ValidationMessageFor(m => @Model.information.Diachi)
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">Email </label>
                                                @Html.TextBoxFor(m => @Model.information.Email)
                                                @Html.ValidationMessageFor(m => @Model.information.Email)
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">SDT </label>
                                                @Html.TextBoxFor(m => @Model.information.SDT)
                                                @Html.ValidationMessageFor(m => @Model.information.SDT)
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">Ngày đăng ký </label>
                                                @Html.TextBoxFor(m => @Model.information.Ngaydangki, (object)new { disabled = "disabled" })
                                            </div>
                                        </div>
                                        <div class="buttons-set">
                                            <input class="btn-black" name="action" type="submit" value="Lưu thay đổi" />
                                        </div>
                                    </fieldset>
                                }
                            </div>
                        </div>

                    </div>
                    <div class="col-sm-6 col-md-6">
                        <div class="account-id">
                            <h4 class="account-title">
                                <span class="fa fa-chevron-right"></span>
                                Thay đổi mật khẩu
                            </h4>
                            <div class="account-form">
                                @using (Html.BeginForm("Thaydoimatkhau", "AccountManager", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)
                                    <fieldset>
                                        <div class="Error">
                                            @if (@Session["Doimatkhau"] != null)
                                            {
                                                <p>@Session["Doimatkhau"]</p>
                                            }
                                        </div>
                                        <div class="login-content">
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">Mật khẩu cũ </label>
                                                @Html.PasswordFor(m => @Model.editPassModel.OldPass)
                                                @Html.ValidationMessageFor(m => @Model.editPassModel.OldPass)
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">Mật khẩu mới </label>
                                                @Html.PasswordFor(m => @Model.editPassModel.Password)
                                                @Html.ValidationMessageFor(m => @Model.editPassModel.Password)
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">Nhập lại mật khẩu </label>
                                                @Html.PasswordFor(m => @Model.editPassModel.ConfirmPassword)
                                                @Html.ValidationMessageFor(m => @Model.editPassModel.ConfirmPassword)
                                            </div>
                                        </div>
                                        <div class="buttons-set">
                                            <input class="btn-black" name="action" type="submit" value="Đổi mật khẩu" />
                                        </div>
                                    </fieldset>
                                }
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>