1212502_1212508_1212526/Frontend_Ecommic/Controllers/SendMailController.cs
using Frontend_Ecommic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Frontend_Ecommic.Controllers
{
    public class SendMailController : Controller
    {
        //
        // GET: /SendMail/
        public ActionResult Index()
        {
            var model = new ContactModels();
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(ContactModels model)
        {
            if (ModelState.IsValid)
            {
                string smtpUserName = "eoooihic@gmail.com";
                string smtpPassword = "eimqcrgljzhzdwwn";
                string smtpHost = "smtp.gmail.com";
                int smtpPort = 25;

                string emailTo = "eooihic@gmail.com"; // Khi có liên hệ sẽ gửi về thư của mình
                string subject = model.Subject;
                string body = string.Format("Bạn vừa nhận được liên hệ từ: <b>{0}</b><br/>Email: {1}<br/>Nội dung: </br>{2}",
                    model.UserName, model.Email, model.Message);

                EmailService service = new EmailService();

                bool kq = service.Send(smtpUserName, smtpPassword, smtpHost, smtpPort,
                    emailTo, subject, body);

                if (kq) ModelState.AddModelError("", "Cảm ơn bạn đã liên hệ với chúng tôi.");
                else ModelState.AddModelError("", "Gửi tin nhắn thất bại, vui lòng thử lại.");
            }
            return View(model);
        }
	}
}

1212502_1212508_1212526/Frontend_Ecommic/Views/SendMail/Index.cshtml
@model Frontend_Ecommic.Models.ContactModels
@{
    ViewBag.Title = "Index";
    <link href="~/Content/css/Account.css" rel="stylesheet" />
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-6">
                        <div class="account-id">
                            <h4 class="account-title">
                                <span class="fa fa-chevron-right"></span>
                                Gửi mail
                            </h4>
                            <div class="account-form">
                                @using (Html.BeginForm("index", "SendMail", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)
                                    <fieldset>
                                        <div class="Error">
                                            @if (@Session["Sendmail"] != null)
                                            {
                                                <p>@Session["Sendmail"]</p>
                                            }
                                        </div>
                                        <div class="login-content">
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">Tên của bạn <span class="required">*</span></label>
                                                @Html.TextBoxFor(m => @Model.UserName)
                                                @Html.ValidationMessageFor(m => @Model.UserName)
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <label for="pass">Email <span class="required">*</span></label>
                                                @Html.TextBoxFor(m => @Model.Email)
                                                @Html.ValidationMessageFor(m => @Model.Email)
                                                @*<input type="submit" value="Log In" class="loginsubmit" />*@
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <label for="name">Chủ đề <span class="required">*</span></label>
                                                @Html.TextBoxFor(m => @Model.Subject)
                                                @Html.ValidationMessageFor(m => @Model.Subject)
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <label for="pass">Nội dung <span class="required">*</span></label>
                                                @Html.EditorFor(m => @Model.Message, new { TextBoxMode = "MultiLine" })
                                                @Html.ValidationMessageFor(m => @Model.Message)
                                                @*<input type="submit" value="Log In" class="loginsubmit" />*@
                                            </div>
                                        </div>
                                        <div class="buttons-set">
                                            <input class="btn-black" name="action" type="submit" value="Send" />
                                        </div>
                                    </fieldset>
                                }
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>