1212502_1212508_1212526/Frontend_Ecommic/Controllers/DonhangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Frontend_Ecommic.Models;

namespace Frontend_Ecommic.Controllers
{
    public class DonhangController : Controller
    {
        // GET: Donhang
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DonhangDetail()
        {
            return View();
        }
        public ActionResult DonhangPartial()
        {
            return View();
        }
    }
}

1212502_1212508_1212526/Frontend_Ecommic/Views/Donhang/DonhangDetail.cshtml
@model List<Frontend_Ecommic.Models.DonhangModel>
<div class="modal fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: block;">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" onclick="closeDialog();">×</button>
                <h3> Chi tiết đơn hàng #@Model.First().Id_SP </h3>
            </div>
            <div class="modal-body">
                <table class="table-hover table-bordered">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.First().sanPham)</th>
                        <th>@Html.DisplayNameFor(model => model.First().soLuong)</th>
                        <th>@Html.DisplayNameFor(model => model.First().Id_SP)</th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.sanPham.TenSanPham</td>
                            <td>@item.soLuong</td>
                            <td>@string.Format("{0:0,0}", @item.Id_SP) </td>
                        </tr>
                    }
                </table>
            </div>
            @*<div class="modal-footer">
                    <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
                    <a href="#" class="btn btn-primary" data-dismiss="modal">Save changes</a>
                </div>*@
        </div>
    </div>
</div>

1212502_1212508_1212526/Frontend_Ecommic/Views/Donhang/Index.cshtml
@{
    ViewBag.Title = "Quản lí đơn hang";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>@ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <div class="alert alert-info" id="alert-info" style="display:none"></div>
                <div class="form-inline" style="text-align: right; padding: 10px">
                    <div class="input-group">
                        @Html.DropDownList("value", new SelectList(new List<object>
                        {
                            new { value = "1" , text = "Dang duyệt"  },
                            new { value = "2" , text = "Đang giao" },
                            new { value = "3" , text = "Đã giao" },
                            new { value = "4" , text = "Hủy" },
                        }, "value", "text"), "--Trạng thái--", new { @class = "form-control", id = "trangthai", onchange = "timkiemdh()" })
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon"><i class="red">Ngày</i></span>
                        <input id="dhday" type="date" class="form-control" onchange="timkiemdh()">
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-search red"></i></span>
                        <input id="mobile" type="text" class="form-control" placeholder="Số điện thoại" oninput="timkiemdh()">
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-search red"></i></span>
                        <input id="madh" type="text" class="form-control" placeholder="Mã đơn hàng" oninput="timkiemdh()">
                    </div>
                    

                </div>
                <div class="form-inline" style="text-align: right; padding: 10px">
                    <div class="input-group">
                        @Html.DropDownList("SetStatus", new SelectList(new List<object>
                        {
                            new { value = "1" , text = "Dang duyệt"  },
                            new { value = "2" , text = "Đang giao" },
                            new { value = "3" , text = "Đã giao" },
                            new { value = "4" , text = "Hủy" },
                        }, "value", "text"), "--- Sửa trạng thái đơn hàng ---", new { @class = "form-control", id = "setstatus" })
                        <span class="input-group-addon" onclick="SetStatus('@Url.Action("MultibleUpdate", "Donhang")')" style="cursor:pointer"><i class="glyphicon glyphicon glyphicon-wrench blue"></i></span>
                    </div>
                </div>

                @*<div class="Ajax-Table" id="Ajax-Table">
                    @Html.Action("TimDonHang", "Donhang")
                </div>*@

            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->